##### Numpy Assignment
Student Name: KATONGOLE MIKE

Reg No: 2022/HD07/5010U

Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem
What is NumPy, and what are some of its key features?

Numpy is a Python library that provides a multidimensional array object, various derived objects such as masked arrays and matrices, and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

some of its key features:

Multidimensional array: NumPy's main feature is the ndarray, an efficient multidimensional array that can hold homogeneous data (i.e., all elements must be of the same data type). These arrays can have any number of dimensions and are the basis for most scientific computing tasks in Python.

Broadcasting: NumPy allows for broadcasting, which means that operations can be performed on arrays with different shapes and sizes. Broadcasting can save time and memory by avoiding the need for explicit looping over the array.

Vectorization: NumPy provides a way to apply mathematical operations to entire arrays, rather than looping over each element. This makes it much faster and more efficient to perform numerical calculations.

Support for linear algebra: NumPy provides functions for linear algebra operations, such as matrix multiplication, inversion, and solving linear systems of equations.


In [3]:
#How do you create a NumPy array using Python's built-in range() function?

# imported numpy as np
import numpy as np

# created a Python list using range()
mtop = list(range(11))

# converted the list to a NumPy array
t_numpy_array = np.array(mtop)

# print the array
print(t_numpy_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


What is the difference between a scalar value and a vector in NumPy?

A vector is an array with one dimension, consisting of a collection of scalar values and is often used to represent quantities that have both a magnitude and a direction while a scalar value is a single numerical value, such as an integer or a floating-point number and that represents a magnitude but has no direction

In [4]:
#How do you calculate the mean of a NumPy array using the mean() function?

# imported numpy as np

import numpy as np

# create a NumPy array
t_numpy_array = np.array([1, 2, 3, 4, 5, 6, 8])

# calculate the mean using mean()
t_Mean = np.mean(t_numpy_array)

# print the mean
print(t_Mean)

4.142857142857143


What is broadcasting in NumPy, and how can it be useful?

Broadcasting in NumPy is the ability of the library to perform operations on arrays with different shapes and sizes. Broadcasting can save time and memory by avoiding the need for explicit looping over the array.

In [5]:
#How do you create a 2D array in NumPy using Python's built-in list of lists?

# imported numpy as np

import numpy as np


# created a list of lists
t_list = [[10, 50, 40], [1, 6, 7], [50, 50, 92]]

# created a 2D array using np.array()
t_array = np.array(t_list)

t_array

array([[10, 50, 40],
       [ 1,  6,  7],
       [50, 50, 92]])

In [20]:
#How can you slice a NumPy array to extract a subarray?

# To slice a NumPy array and extract a subarray, you can use the slicing notation arr[start:stop:step], where "start" is the index of the first element of the subarray, "stop" is the index of the last element of the subarray (exclusive), and "step" is the spacing between the elements.

# Example include:

# we first import numpy as np

import numpy as np

# Creating an array

t_numpy_arry = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
 
#Sliced that array

slicedArray = t_numpy_arry[2:3]

# print sliced array

print(slicedArray)





[3]


#What are some of the available functions for performing element-wise operations on NumPy arrays?

There are a variety of element-wise functions that can be applied to  arrays in numpy and these include. 

numpy.sin(),numpy.cos(), numpy.logical_and(), numpy.logical_or(), numpy.arcsin(),  numpy.median(), numpy.prod(), etc

In [23]:
#How do you reshape a NumPy array to have a different shape?

# We use the reshape() function. The reshape() method returns a new array with the same data but a different shape. The new shape must have the same number of elements as the original shape, otherwise, a ValueError will be raised.

#For example:

# imported numpy as np

import numpy as np

# created a 1D array with 12 elements

t_arry = np.arange(12)

 # reshaped the array to a 3x4 2D array

t_new_arry = t_arry.reshape((3, 4))

# Printing the reshaped array

print(t_new_arry)





[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
#How do you perform matrix multiplication on two NumPy arrays using the dot() function?


#The dot() function can be used to perform matrix multiplication on two-dimensional arrays as well as on higher-dimensional arrays 

# imported numpy as np

import numpy as np

# Created two 2x3 arrays

t_arry_1 = np.array([[18, 21, 70], [29, 6, 80]])
t_arry_2 = np.array([[16, 78], [88, 17], [19, 92]])

# Used the dot() function to multiply

t_arry = np.dot(t_arry_1, t_arry_2)

#printe the result

print(t_arry)


[[3466 8201]
 [2512 9724]]


In [26]:
#How can you use the where() function to apply a condition to a NumPy array?

# The where() function in NumPy allows you to apply a condition to an array and return a new array with values that meet the condition replaced by a specified value, and values that do not meet the condition replaced by another specified value.

# The syntax of this function is numpy.where(condition, x, y)

# imported numpy as np

import numpy as np

# created an example array
ex_arry = np.array([1, 2, 3, 4, 5, 6])

# applyed a condition and replace values
ex_new_arry = np.where(ex_arry > 3, 10, ex_arry)

# print the new array
print(ex_new_arry)


[ 1  2  3 10 10 10]


What is the difference between the flatten() and ravel() functions in NumPy?

flatten() function returns a copy of the array, collapsed into a one-dimensional array. The returned array is always a copy of the original array, even if the original array was already one-dimensional. This means that any changes made to the returned array will not affect the original array While ravel() function also returns a one-dimensional array, but it may return a view of the original array instead of a copy. If the array is already one-dimensional, then ravel() will return a view of the original array. This means that changes made to the returned array may affect the original array as well







In [27]:
#How do you use NumPy's advanced indexing capabilities to select specific elements from an array?

# Indexing with arrays of indices: 
# Use an array of integers to select specific elements from an array.

# imported numpy as np
import numpy as np

# created an array
ind_arry = np.array([[1, 2], [3, 4], [5, 6]])

# Selected specific elements
print(ind_arry[[0, 1, 2], [0, 1, 0]]) # Output: [1 4 5]

# Selected a subset of rows
print(ind_arry[[0, 2]]) # Output: [[1 2]
                   #         [5 6]]
        



[1 4 5]
[[1 2]
 [5 6]]


In [29]:
#How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

# we import the numpy package
import numpy as np



broad_arry_1 = np.array([1, 2, 3])
broad_arry_2 = np.array([[4], [5], [6]])

ypy = broad_arry_1 + broad_arry_2

print(ypy) #Output [[5 6 7]
                #  [6 7 8]
                #  [7 8 9]]

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [32]:
#How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?

#To perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors, you can use the numpy.errstate 

# Example:

import numpy as np

div_arry_1 = np.array([13, 23, 32])
div_arry_2 = np.array([0, 30, 0])

with np.errstate(divide='ignore', invalid='ignore'):
    ypy = np.true_divide(div_arry_1, div_arry_2)

print(ypy)



[       inf 0.76666667        inf]


### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [ ]:
# Prompt the user to enter a list of numbers separated by commas
prompt = input("Enter a list of numbers separated by commas: ")

# Convert the input into a 1D NumPy array
prompt  = np.array([float(x) for x in prompt.split(',')])

# Calculate the statistics using NumPy functions
Mean = np.mean(prompt)
Median = np.median(prompt)
Std_dev = np.std(prompt)
Max_val = np.max(prompt)
Min_val = np.min(prompt)

# Display the statistics with appropriate labels
print("Statistics:")
print("Mean: ", Mean)
print("Median: ", Median)
print("Standard Deviation: ", Std_dev)
print("Maximum Value: ", Max_val)
print("Minimum Value: ", Min_val)