## Numpy Assignment
Student Name: 2200702040

Reg No:2022/HD07/2040U

## Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

In [ ]:
# What is NumPy, and what are some of its key features?

Numpy is the short form for Numeric python.
It is a python library/package for performing mathematical (numerical) operations on large, multidimensional data structures (arrays, matrices).
It also provides a foundation upon which other python libraries base on to perform their functions.

##### Key features of NumPy include:
# - Easy Integration with other Python libraries, like pandas, matplotlib, SciPy, enabling analysis and data visulaization
# - Multidimensional arrays = N-dimensional objects (matrices, vectors, etc)
# - Ability to effiiently perform element-wise operations (additions, subtractions, multiplication, division, exponentiations, etc)
# - Wide range of Mathematical functions, including linear algebra functions like matrix multiplicaion.
# - Allows for Broadcasting, which enables operations on arrays of different shapes and sizes.
# - Powerful Indexing and slicing capability, enabling access and modification of elements within arrays.
# - Efficient memory use

In [ ]:
# NumPy is first of all a package for scientific computing in Python. It provides a multidimensional array object, various derived objects and an assortment of routines for fast operations on arrays.

#some of its key features include. N-dimensional arrays, mathematical functions, Indexing, slicing

In [ ]:
#How do you create a NumPy array using Python's built-in range() function?

First, we call the numpy package/library with the alias np in order to be able to execute numpy operations, using the import function as below:

In [1]:
import numpy as np

In [2]:
# You can create a numpy array using the python builtins range function by first creating a python list using the range() function and then converting it into an array using the numpy.array function.
# an array with values from 0 to 9
array1 = np.array(range(10))
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#What is the difference between a scalar value and a vector in NumPy?


In [3]:
#A scalar is a single value or quantity while a vector is a one dimensional array of values.


scalar1 = np.array(42)
scalar2 = np.array(12.6)
print(scalar1)

vector1 = np.array([1,2,3,4,67])
print(vector1)

42
[ 1  2  3  4 67]


In [4]:
#How do you calculate the mean of a NumPy array using the mean() function?

In [5]:
array1 = np.array(range(10))
print(array1)
mean_array1 = np.mean(array1)
print(mean_array1)

[0 1 2 3 4 5 6 7 8 9]
4.5


In [ ]:
#What is broadcasting in NumPy, and how can it be useful?

In [6]:
# Broadcasting is a feature in Numpy that allows arithmetic operations to be perfomed on arrays of different shapes amd sizes. It allows smaller arrays to be broadcast to the shape of the larger arrays so that element wise operations can be perfomed.

# 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
# 1D array
b = np.array([10, 20, 30])
print(b)

# Adding the 1D array; the 1D array is padded to each row of the 2D array using broadcasting
c = a + b

# Print the result
print(c)

[[1 2 3]
 [4 5 6]]
[10 20 30]
[[11 22 33]
 [14 25 36]]


In [ ]:
#How do you create a 2D array in NumPy using Python's built-in list of lists?

In [7]:
# One can use the numpy.array method and then pass in the list of lists as an argument.

#  create a list of lists
main_list = [[1,2,3,4], [10,12,14,16], [20,30,40,50]]
print(main_list)

# convert list into array
list_array = np.array(main_list)
print(list_array)
type(list_array)

[[1, 2, 3, 4], [10, 12, 14, 16], [20, 30, 40, 50]]
[[ 1  2  3  4]
 [10 12 14 16]
 [20 30 40 50]]


numpy.ndarray

In [ ]:
#How can you slice a NumPy array to extract a subarray?

In [8]:
# By using the indexing method and the colon notation, the general syntax is "new_array = old_array[start:stop:step]"


# create an array:
array_1 = np.array([[1,2,3,5], [2,5,6,8], [10,45,55,60]])
type(array_1)

# create a subarray:
subarray1 = array_1[0:3, 1:4] # rows 1 to 3 (index 0 to 3-1), and cols 2 to 4 (index 1 t0 4-1) #the -1 rule applies for the last index
print(subarray1)

subarray2 = array_1[1:3, 2:4] # rows 2 to 3 (index 1 to 3-1), cols 3 to 4 (index 2 to 4-1)
print(subarray2)

[[ 2  3  5]
 [ 5  6  8]
 [45 55 60]]
[[ 6  8]
 [55 60]]


In [ ]:
#What are some of the available functions for performing element-wise operations on NumPy arrays?

In [9]:
d = np.array([1,2,3,4])
e = np.array([7,8,9,10])

# np.add() for element-wise addition of arrays
array_add = np.add(d, e)
print(array_add)

# np.subtract() for element-wise subtraction
array_sub = np.subtract(d, e) # array d minus e
print(array_sub)

# np.multiply() for element-wise multiplication
array_mult = np.multiply(d,e)
print(array_mult)

# np.divide() for element-wise division
array_div = np.divide(d, e)
print(array_div)

# np.power() for element-wise exponentiation (a number to the power)
array_pow = np.power(e, d) # elements of array e to the power of corresponding elements of array d
print(array_pow)

# np.sqrt() for element-wise square root of each element of an array
array_sq = np.sqrt(d)
print(array_sq)

array_exp = np.exp(d)
print(array_exp)

[ 8 10 12 14]
[-6 -6 -6 -6]
[ 7 16 27 40]
[0.14285714 0.25       0.33333333 0.4       ]
[    7    64   729 10000]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
#How do you reshape a NumPy array to have a different shape?

In [10]:
# One can reshape a NumPy array using the reshape() method. The reshape() method returns a new array with the same data but a different shape. The new shape must have the same number of elements as the original shape.

f = np.array([1,2,3,4,5,6])
print(f)

# using the reshape() function
g = f.reshape(2, 3) # the dimensions of the new array must be multiples of the size of the original array
print(g)
h = f.reshape(3,2) # 3 rows, 2 columns
print(h)
i = f.reshape(6,1) # 6 rows, 1 column
print(i)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
#How do you perform matrix multiplication on two NumPy arrays using the dot() function?

In [ ]:
# you can perform matrix multiplication on two NumPy arrays using the dot() function. The dot() function can be used to compute dot products between vectors, as well as matrix multiplication between matrices. 

#### How do you perform matrix multiplication on two NumPy arrays using the dot() function?
# Matrix multiplication of arrays follows the following rules:
# - the number of columns in the 1st array == to the number of rows in second array
# - the resulting array must have the same number of rows as the first array, and same number of columns as the second array
# - The element at position (i, j) in the resulting matrix is obtained by multiplying the elements of the ith row of the first array with the corresponding elements of the jth column of the second array, and then summing the products
# Consider two arrays below:

In [11]:
k = np.array([[1,2, 3],[3,4, 8]])
print(k)
l = np.array([5,6,7])
print(l)
# # using the dot() function
m = k.dot(l)
print(m)

# the @ operator can also be used to multiply arrays
n = k @ l
print(n)

[[1 2 3]
 [3 4 8]]
[5 6 7]
[38 95]
[38 95]


In [ ]:
#How can you use the where() function to apply a condition to a NumPy array?

In [ ]:
# You can use the where() function in NumPy to apply a condition to an array and return a new array with the same shape as the original array, where the elements that satisfy the condition are replaced by a specified value, and the elements that do not satisfy the condition are replaced by another specified value. You can also use the where() function to apply a condition to two arrays and return a new array with the same shape as the original arrays, where the elements that satisfy the condition are taken from the first array, and the elements that do not satisfy the condition are taken from the second array.
#### How can you use the where() function to apply a condition to a NumPy array?
#  zero is returned for elements that do not satisfy the condition.
# the .where() fucntion takes these arguments;
#         numpy.where(condition, x, y)
#         - x is the value returned if condition is True
#         - y is the value returned if condition is false
# consider the array below:

In [12]:
array5 = np.array([1,2,3,4,5,6,8])
array6 = np.where(array5 <=3, array5, 0)
print(array6)

[1 2 3 0 0 0 0]


In [ ]:
#What is the difference between the flatten() and ravel() functions in NumPy?

In [13]:
# flatten() and ravel() are similar functions that can be used to convert a multidimensional array into a one-dimensional array. The main difference is that flatten() always returns a copy of the original array, whereas ravel() returns a flattened view of the original array whenever possible.

array7 = np.array([[1,2,3], [4,5,6]])
print(array7)
# flatten()
array_flat = array7.flatten()
print(array_flat)

# modifying the flattened array
array_flat[2] = 100 # replace element at index 2 with 100
print(array_flat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[  1   2 100   4   5   6]


In [14]:
# ravel()
array8 = np.array([[8,9,10], [12,13,15]])
print(array8)

# ravel array
array_rav = array8.ravel()
print(array_rav)

# modify the raveled array
array_rav[1] = 3
print(array_rav)

print(array8) 

[[ 8  9 10]
 [12 13 15]]
[ 8  9 10 12 13 15]
[ 8  3 10 12 13 15]
[[ 8  3 10]
 [12 13 15]]


In [ ]:
#How do you use NumPy's advanced indexing capabilities to select specific elements from an array?

In [ ]:
# NumPy provides a powerful indexing syntax that allows you to select specific elements or subsets of an array. This indexing syntax is called "advanced indexing" and it allows you to select elements based on Boolean masks, integer arrays, and even other arrays.


# This can be done using either Boolean (boolean-like) inde arrays, or using integer arrays.


In [15]:
##### a) using Boolean index arrays.
# These are arrays containing True or False values. Only elements that correspond to the True index are selected.
# Consider the example below:


array9 = np.array([10,11,15,20,25])
boolean_index = np.array([True, False, True, False, True])

result = array9[boolean_index]
print(result)

[10 15 25]


In [16]:
# ##### b) using the integer array
# This array contains indices of elements you want to select, in form of integers.
# Consider example below:

array10 = np.array([10, 'x', 'mango', 20, 'okra'])
integer_index = np.array([0, 1, 3, 4])

outcome1 = array10[integer_index]
print(outcome1)

['10' 'x' '20' 'okra']


In [ ]:
#How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

In [17]:
# NumPy's broadcasting rules allow you to perform operations on arrays with different shapes. The broadcasting rules apply when the arrays being operated on have different shapes, but are still compatible for the operation. The rules allow NumPy to perform the operation as if the arrays had the same shape, by stretching or duplicating one or both arrays as needed.
# It follows the broadcasting rules below:
# - For arrays with different diensions, the smaller array is padded to the larger one.
# - If arrays have different shapes, the one with a shape equal to 1 is stretched to match the shape of the other array.
# - If neither of the aboe, NumPy throws a "ValueError: operands could not be broadcast together" error.




array11 = np.array([[1,2,3], [5,6,8]])
array12 = np.array([3,6,9])
scalar3 = np.array(10)

# for 1D and 2D arrays
outcome2 = array11 + array12 # elements of array12 are added element-wise to each of the nested lists of array11
print(outcome2)

# for 2D array and scalar
outcome3 = array11 + scalar3 # the scalar is added to each element of array11
print(outcome3) 


[[ 4  8 12]
 [ 8 12 17]]
[[11 12 13]
 [15 16 18]]


In [ ]:
#How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?

In [18]:
array11 = np.array([20, 24, 32, 40, 0])
array12 = np.array([10, 0, 8, 14, 25])

with np.errstate(divide='ignore'):
    outcomes = np.divide(array11, array12)
print(outcomes)



[2.                inf 4.         2.85714286 0.        ]


### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [19]:
import numpy as np
# prompt for entering comma seperated numbers
num_str = input('Enter numbers separated by commas: ')

# convert the strings into integers
nums = np.fromstring(num_str, dtype=int, sep=',')
print(nums)
print('Statistics for the input array:')

# mean of numbers
mean = np.mean(nums)
print('Mean is', mean)

# median of numbers
median = np.median(nums)
print('Median is', median)

# standard deviation
std_dev = np.std(nums)
print('Standard deviation is', std_dev)

# maximum
maximum = np.max(nums)
print('The maximum number is', maximum)

# minimum
minimum = np.min(nums)
print('Minimum value is', minimum)

[2 3 4]
Statistics for the input array:
Mean is 3.0
Median is 3.0
Standard deviation is 0.816496580927726
The maximum number is 4
Minimum value is 2
