## Numpy Assignment
Student Name:Wanyama Emmanuel Okuku

Reg No:2022/HDO7/5015U

## Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

### What is NumPy, and what are some of its key features?
 NumPy is a Python library that stands for "Numerical Python".
It is an essential package for scientific computing in Python and provides an efficient interface to store 
and operate on dense data buffers, as well as tools for working with arrays. 

The features include; 
- Multidimensional arrays
- Mathematical functions
- Broadcasting
- Indexing and slicing
- Efficient memory use
- Integration with other libraries:

### How do you create a NumPy array using Python's built-in range() function?

In [ ]:
import numpy as np #Import Numpy
Wanyama = np.array(range(10)) ##use the np.array() function to create a NumPy array from the range object range(10)
print(Wanyama)

[0 1 2 3 4 5 6 7 8 9]


### What is the difference between a scalar value and a vector in NumPy?

A scalar is a single numeric value (integer or float), while a vector is a collection of scalar values.
As indicated below:

In [7]:
import numpy as np
scalar1 = np.array(42)
scalar2 = np.array(12.6)
print(scalar1)
print(scalar2)

vector1 = np.array([2,6,9,50,70])
print(vector1)

42
12.6
[ 2  6  9 50 70]


### How do you calculate the mean of a NumPy array using the mean() function?

In [36]:
import numpy as np
Emma = np.array(range(11))
print(Emma)
mean_Emma = np.mean(Emma)
print(mean_Emma)

[ 0  1  2  3  4  5  6  7  8  9 10]
5.0


### What is broadcasting in NumPy, and how can it be useful?

In NumPy, broadcasting refers to the implicit and automatic alignment of arrays with different shapes during arithmetic operations. When NumPy tries to perform an operation between two arrays of different shapes, broadcasting allows the smaller array to be broadcasted to match the shape of the larger array.
For example, in the case where we have two arrays:



In [37]:
import numpy as np
# 2D array
pam = np.array([[5, 6, 7], [8, 9, 10]])
print(pam)
# 1D array
jael = np.array([30, 40, 50])
print(jael)

# Adding the 1D array; the 1D array is padded to each row of the 2D array using broadcasting
Emma = pam + jael

# Print the result
print(Emma)


[[ 5  6  7]
 [ 8  9 10]]
[30 40 50]
[[35 46 57]
 [38 49 60]]


In [38]:
import numpy as np
# Another example
#2D array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Adding a and b
c = a + b
# Resulting into
print(c)

# NumPy will automatically broadcast the smaller array a to match the shape of the larger array b,

[5 7 9]


Broadcasting can be useful in a variety of situations:

1.Vectorization of code: Broadcasting can simplify code that operates on arrays by allowing operations to be performed element-wise on arrays of different shapes.

2.Avoiding unnecessary memory allocation: Broadcasting allows NumPy to perform operations on arrays of different shapes without having to allocate memory for a new array.

3.Improving performance: Broadcasting can be much faster than looping over arrays and performing element-wise operations manually.

### How do you create a 2D array in NumPy using Python's built-in list of lists?

In [39]:
import numpy as np
# Create a list of lists
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Convert the list of lists to a NumPy array
my_array = np.array(my_list)

# Print the array
print(my_array)

# NB:the resulting array has a shape of (3, 3) indicating that it has three rows and three columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
import numpy as np
#Another example
# create a list of lists
Emma_list = [[1,2,3,4], [10,12,14,15], [20,30,40,50]]
print(Emma_list)

list_array = np.array(Emma_list)
print(list_array)
type(list_array)

[[1, 2, 3, 4], [10, 12, 14, 15], [20, 30, 40, 50]]
[[ 1  2  3  4]
 [10 12 14 15]
 [20 30 40 50]]


numpy.ndarray

### How can you slice a NumPy array to extract a subarray?

You can slice a NumPy array to extract a subarray by specifying the indices of the elements you want to extract. The syntax for slicing a NumPy array is array[start:stop:step], where start is the index of the first element, stop is the index of the last element (exclusive), and step is the step size.

In [40]:
# create an array:
array_z = np.array([[1,2,3,5], [2,5,6,8], [10,45,55,60]])
type(array_z)

# create a subarray:
subarray1 = array_z[0:4, 1:4] # rows 0 to 3, and cols 1 to 3 #the -1 rule applies for the last index
print(subarray1)

subarray2 = array_z[1:3, 2:5] # rows 1 to 2, cols 2 to 4
print(subarray2)

[[ 2  3  5]
 [ 5  6  8]
 [45 55 60]]
[[ 6  8]
 [55 60]]



### What are some of the available functions for performing element-wise operations on NumPy arrays?
- numpy.add():  Adds corresponding elements in two arrays.
- numpy.subtract():  Subtracts corresponding elements in two arrays.
- numpy.multiply():  Multiplies corresponding elements in two arrays.
- numpy.divide():  Divides corresponding elements in two arrays.
- numpy.power():  Raises corresponding elements in an array to a specified power.
- numpy.sqrt():  Computes the square root of each element in an array.
- numpy.exp():  Computes the exponential of each element in an array.
- numpy.log():  Computes the natural logarithm of each element in an array.

### How do you reshape a NumPy array to have a different shape?
You can reshape a NumPy array to have a different shape using the reshape() function. 
The reshape() function returns a new array that has the same data as the original array, but with a different shape. 
The new shape must be compatible with the size of the original array.

In [15]:
import numpy as np
# create a 1D array with 15 elements
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
# Reshape the array into a 2D array with 5 rows and 3 columns
array2d = array1.reshape((5, 3))
print(array2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### How do you perform matrix multiplication on two NumPy arrays using the dot() function?
The dot() function computes the dot product of two arrays, which is the matrix multiplication of the two arrays if they are 2D arrays.
For Example;

In [19]:
import numpy as np
# create two 2D arrays
P = np.array([[1, 10], [3, 10]])
Q = np.array([[5, 20], [7, 20]])
# perform matrix multiplication using dot() function
R = np.dot(P, Q)
print(R)

[[ 75 220]
 [ 85 260]]


### How can you use the where() function to apply a condition to a NumPy array?
You can use the where() function in NumPy to apply a condition to an array and return a new array with elements that satisfy the condition.
where() function returns a new array with the same shape as the input array, where elements that satisfy the condition are replaced by the corresponding elements from the input array, and elements that do not satisfy the condition are replaced by the value provided as the third argument

In [21]:
import numpy as np
# create a 1D array with 5 elements
array = np.array([1, 2, 3, 4, 5])
# create a new array with elements from array that are greater than 3
new_array = np.where(array > 3, array, 0)
print(new_array)

[0 0 0 4 5]


In [25]:
import numpy as np
#Another example
# create a 1D array with 7 elements
ar = np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G'])
# create a new array with elements from ar that are greater than 'D'ArithmeticError
new_ar = np.where(ar > 'D', ar, 0)
print(new_ar)

['0' '0' '0' '0' 'E' 'F' 'G']


### What is the difference between the flatten() and ravel() functions in NumPy?
In NumPy, both the flatten() and ravel() functions are used to convert a multidimensional array into a one-dimensional array. However, there is a subtle difference between the two functions;
The flatten() function always returns a copy of the array, whereas the ravel() function returns a view of the original array whenever possible, and only creates a copy if necessary.
The flatten() function returns a new copy of the original array, so modifying the original array has no effect on the flattened array. On the other hand, the ravel() function returns a view of the original array whenever possible, so modifying the original array also affects the flattened array.

In [26]:
import numpy as np
# create a 2D array
ay = np.array([[1, 2], [3, 4]])
# use flatten() function to create a new flattened array
ay_flattened = ay.flatten()
# use ravel() function to create a new flattened array
ay_raveled = ay.ravel()
# modify original array
ay[0, 0] = 5
print(ay_flattened)
print(ay_raveled)

[1 2 3 4]
[5 2 3 4]


### How do you use NumPy's advanced indexing capabilities to select specific elements from an array?
NumPy's advanced indexing capabilities allow you to select specific elements from an array based on conditions or specific indices. 
For Example;

### You can use Boolean index arrays as below

In [43]:
import numpy as np
# Create a 1D array
Emma = np.array([100, 200, 300, 400, 500])
# Select elements boolean indices
boolean_index = np.array([True, True, False, True, False])

Result = Emma[boolean_index]
print(Result)

[100 200 400]


### Alternatively you can use integer arrays which contain indices of elements you want to select in integer form

In [48]:
import numpy as np
# Create a 1D array
Emmaw = np.array(['pistol', 'magazine', 7, 'Tom', 'Lord'])
# Select elements at specific indices
integer_index = np.array([0, 1, 4])

outcome = Emmaw[integer_index]
print(outcome)

['pistol' 'magazine' 'Lord']


In [61]:
import numpy as np

# Create a 1D array
y = np.array([1, 2, 3, 4, 5])

# Select elements at specific indices
indices = np.array([0, 2, 4])
result = y[indices]
print(result) 

[1 3 5]


### How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?
NumPy's broadcasting rules allow you to perform operations on arrays with different shapes.
 Broadcasting is a powerful tool that allows NumPy to work with arrays of different shapes and sizes. It enables you to perform operations on arrays without explicitly creating copies of the data.

If two arrays have different shapes, but their dimensions match in some way, you can use them together in an operation. When performing an operation on two arrays, NumPy compares their shapes element-wise. 
If the dimensions of the arrays are not the same, but they are compatible according to the broadcasting rules, NumPy will broadcast one or both of the arrays to match the dimensions of the other.


### How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?
Use the numpy.divide() function along with the numpy.errstate()

In [58]:
import numpy as np
# sample arrays
J = np.array([5, 2, 3, 0, 7])
K = np.array([0, 1, 2, 3, 0])

# "ignore" any divide-by-zero
with np.errstate(divide='ignore', invalid='ignore'):
# perform element-wise division while ignoring divide-by-zero errors
    L = np.divide(J, K)
print(L)

[inf 2.  1.5 0.  inf]


### Alternatively

In [56]:
import numpy as np

# sample arrays
u = np.array([3, 2, 4, 0, 5])
v = np.array([0, 2, 0, 4, 5])

# ignore divide-by-zero warning
np.seterr(divide='ignore', invalid='ignore')

# perform element-wise division while ignoring divide-by-zero errors
w = np.divide(u, v)

print(w)

[inf  1. inf  0.  1.]


### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [49]:
import numpy as np
# Prompt the user to enter a list of numbers separated by commas
input_str = input("Enter a list of numbers separated by commas: ")

# Convert the input into a 1D NumPy array
nums = np.fromstring(input_str, dtype=int, sep=',')

# Calculate the mean of the numbers
mean = np.mean(nums)

# Calculate the median of the numbers
median = np.median(nums)

# Calculate the standard deviation of the numbers
std = np.std(nums)

# Calculate the maximum value of the numbers
max_val = np.max(nums)

# Calculate the minimum value of the numbers
min_val = np.min(nums)

# Display the statistics with appropriate labels
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std)
print("Maximum value: ", max_val)
print("Minimum value: ", min_val)

Mean:  4.5
Median:  4.0
Standard Deviation:  2.8136571693556887
Maximum value:  9
Minimum value:  1
