## Numpy Assignment
Student Name: Katairo Thomas

Reg No: N/A

## Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

### What is NumPy, and what are some of its key features?

NumPy  is a Python library used for numerical computations and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of mathematical functions to operate on these arrays.

Some of the features of NumPy include
1. ndarray: This is used to represent arrays of arbitrary dimensions
2. Mathematical functions: Numpy provides different mathematical functions for performing operations on arrays, such as addition, subtraction, multiplication, division and more
3. Broadcasting
4. Indexing and slicing
5. Linear algebra
6. Random number generation
7. Memory management

### How do you create a NumPy array using Python's built-in range() function?



In [2]:
import numpy as np # Call up numpy
a = np.array(range(10)) # Make an array of range 10
print(a)


[0 1 2 3 4 5 6 7 8 9]


### What is the difference between a scalar value and a vector in NumPy?

A scalar value is a single value or number, such as an integer or a floating-point number, that can be represented using a single data type. This has 0 dimensional array

A vector is a collection of values, often of the same data type, that are organized in a specific order. A vector is a 1-dimensional array. 

How to create these 2 can be done as below

In [3]:
b = np.array(42) # For scalar
print(b)

c = np.array([1,2,3,4,5]) # For vector
print(c)

42
[1 2 3 4 5]


### How to calculate the mean using the mean() function

In [9]:
d = c.mean()
print(d)

3.0


### What is broadcasting in NumPy, and how can it be useful?

Broadcasting is a feature in NumPy that allows arrays of different shapes to be used together in arithmetic operations. This is a set of rules that apply when performing operations on arrays with different shapes, allowing NumPy to perform the operation even if the arrays have different sizes or shapes.

When operating on two arrays, NumPy compares their shapes element-wise, starting with the rightmost dimension and working backwards. Two dimensions are considered compatible if they are equal, or if one of them is 1. If the dimensions are not compatible, NumPy will generate a "ValueError" indicating that the shapes are not compatible.


### How do you create a 2D array in NumPy using Python's built-in list of lists?

In [10]:
e = np.array([[1,2], [3,4]])
print(e)

[[1 2]
 [3 4]]


### How can you slice a NumPy array to extract a subarray?

This can be done by specifying the indices to be extracted using the syntax [start:stop:step]. Start is where you want to start from, stop is the stop index and step is the jumping side. An example is below

In [15]:
f = np.array([[1,2,3], [4,5,6],[7,8,9]])
g = f[:2, :3] # Extract the first 2 rows and 3 columns
print(g)

[[1 2 3]
 [4 5 6]]


### What are some of the available functions for performing element-wise operations on NumPy arrays?

1. Arithmetic operations:
   np.add(): add arrays element-wise

   np.subtract(): subtract arrays element-wise

   np.multiply(): multiply arrays element-wise

   np.divide(): divide arrays element-wise
   
   np.power(): raise arrays to a power element-wise

2. Trigonometric functions:
   
   np.sin(): compute sine element-wise
   
   np.cos(): compute cosine element-wise
   
   np.tan(): compute tangent element-wise
   
   np.arcsin(): compute inverse sine element-wise
   
   np.arccos(): compute inverse cosine element-wise
   
   np.arctan(): compute inverse tangent element-wise

3. Exponential and logarithmic functions:
 
   np.exp(): compute exponential element-wise
   
   np.log(): compute natural logarithm element-wise
   
   np.log10(): compute base-10 logarithm element-wise
   
   np.log2(): compute base-2 logarithm element-wise

1. Other functions:
   
   np.abs(): compute absolute values element-wise
   
   np.sqrt(): compute square roots element-wise
   
   np.round(): round elements to

### How do you reshape a NumPy array to have a different shape?

We can use the reshape() method like in the code below

In [16]:
h = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
i = h.reshape(3, 3)
print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### How do you perform matrix multiplication on two NumPy arrays using the dot() function?

In [19]:
# Create two NumPy arrays of dimensions 2x3 and 3x2
j = np.array([[1, 2, 3], [4, 5, 6]])
k = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication using dot()
l = np.dot(j, k)

# Print the result
print(l)

[[ 58  64]
 [139 154]]


### How can you use the where() function to apply a condition to a NumPy array?

The where() function in NumPy can be used to apply a condition to a NumPy array and return a new array with values based on the condition.

In [22]:
m = np.array([1, 2, 3, 4, 5]) # Create a NumPy array

n = np.where(m > 2, m, 0) # Apply a condition to the array

print(n)

[0 0 3 4 5]


### What is the difference between the flatten() and ravel() functions in NumPy?

Both flatten() and ravel() can be used to flatten multi-dimensional arrays into a 1D array. However, the differences between the two are:

1. Flatten() returns a copy of the array, whereas ravel() returns a view of the array. This means that changes made to the returned array in ravel() will be reflected in the original array, whereas changes made in flatten() will not.

2. Flatten() always returns a copy of the original array, even if the original array is already one-dimensional. ravel(), on the other hand, returns a view of the original array if possible, which can be faster and more memory-efficient. An example is below

In [28]:
# create a 2D array
arr = np.array([[1, 2, 3], [3, 4, 4]])
# use flatten() function to create a new flattened array
arr_flattened = arr.flatten()

arr_raveled = arr.ravel()
# modify original array
arr[0, 0] = 5
print(arr_flattened)
print(arr_raveled)

[1 2 3 3 4 4]
[5 2 3 3 4 4]


### How do you use NumPy's advanced indexing capabilities to select specific elements from an array?
There are 2 types of NumPy's advanced indexing capabilities. These include
1. Integer indexing: Using an array of integers to select specific elements from an array
2. Boolean indexing: We can use boolean values to select specific elements from an array

In [31]:
# For integer indexing
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[[0, 1], [0, 1]])


# For Boolean indexing
arr = np.array([[1, 2], [3, 4], [5, 6]])
mask = arr > 2
print(arr[mask]) 

[1 4]
[3 4 5 6]


### How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

NumPy's broadcasting rules allow the performance of element-wise operations on arrays with different shapes. This is a powerful feature of NumPy that enables you to perform operations on arrays of different sizes and shapes without having to create a new copy of the data.

The broadcasting rules in NumPy are as follows:

1. If two arrays have the same shape, they can be operated on element-wise.
2. If two arrays have different shapes, but the dimensions of the arrays are compatible, NumPy will broadcast the smaller array over the larger array to make the shapes compatible.
3. If two arrays have different shapes and are not broadcastable, NumPy will raise a ValueError.

### How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?

We can use the numpy.divide() function with the numpy.errstate() context manager. The code is below



In [32]:
a = np.array([1, 2, 3])
b = np.array([0, 2, 0])

with np.errstate(divide='ignore', invalid='ignore'):
    c = np.divide(a, b)

print(c)

[inf  1. inf]


### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [33]:
numbers = input("Enter the numbers you want to calculate for separated by a comma: ")
nums = np.fromstring(numbers, dtype=int, sep=',')
mean = np.mean(nums) # Get mean
median = np.median(nums) #Get median
sd = np.std(nums) #Get standard deviation
max = np.max(nums) #Get maximum value
min = np.min(nums) #Get minimum value

print("Mean: ", mean)
print("Median: ", median)
print("Standarx Deviation: ", sd)
print("Maximum value: ", max)
print("Minimum value: ", min)

Mean:  15.375
Median:  11.5
Standarx Deviation:  13.378504213849917
Maximum value:  47
Minimum value:  2
