## Numpy Assignment
Student Name: KAKANDE Paul

Reg No: 2022/HD07/2044U

## Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

In [1]:
# Importing numpy package and aliasing it as np
import numpy as np

In [2]:
# What is NumPy, and what are some of its key features?

#### Defining NumPy and its key features.

Numpy short for _Numerical Python_, is one of the foundational packages for numerical computing in python.

**Features**
- ndarray, an efficient multidimensional array that provides fast array-oriented arithmetic operations and flexible broadcasting capabilities.
- Mathematical functions for fast operations on entire arrays of data without having to write loops, that is vectorisation.
- Tools for reading and writing array data to disk and working with memory-mapped files.
- Linear algebra, random number generation, and Fourier transform capabilities.
- A C API for connecting NumPy with libraries written in C, C++, or FORTRA

In [3]:
#How do you create a NumPy array using Python's built-in range() function?

#### Creating a NumPy array using Python's built-in range() function.

Python's built-in `range()` returns a range object, a sequence of integers.

Use case: <br/>
`range(stop)` <br/>
`range(start, stop \[,step\])` <br/>
where in the first instance start defaults to zero. In both, it returns a range object that produces a sequence ranging from start inclusive to stop exclusive by step as the increment or decrement from the start. Start, Stop and Step should be integers.


To create a NumPy array from the returned object;
- Convert the `range()` iterable to a list using `list(range())`
- Convert the created list to NumPy array using the array function of numpy as `numpy.array(list [,dtype=dtype])`

The use case is shown in the next code block.

**Note**<br/>
The parameters in square brackets "`[]`" are not mandatory.<br/>
dtype specifies the datatype to be used for the array.

In [4]:
# Creating the NumPy array from the range built-in function
arr_from_range = np.array(list(range(10)))

# Displaying the created array
arr_from_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#What is the difference between a scalar value and a vector in NumPy?

#### Difference between a scalar and a vector in NumPy.

A scalar is a single value; these can be obtained using the `np.ScalarType` function. Examples are:
- int
- float64
among others. These form the individual units of the NumPy arrays.

A vector is an array with one dimension. It could be a column vector or a row vector.

The code block below shows the distinction.

In [6]:
# printing out the scalar types in NumPy
print("NumPy Scalar types:\n",np.ScalarType)

# printing a column vector
print("Column Vector:\n", np.array([[1],[2],[3],[4]]).shape)

# printing a row vector
print("Row Vector:\n",np.array([1,2,3,4]))

NumPy Scalar types:
 (<class 'int'>, <class 'float'>, <class 'complex'>, <class 'int'>, <class 'bool'>, <class 'bytes'>, <class 'str'>, <class 'memoryview'>, <class 'numpy.bool_'>, <class 'numpy.complex64'>, <class 'numpy.clongdouble'>, <class 'numpy.complex128'>, <class 'numpy.float16'>, <class 'numpy.float32'>, <class 'numpy.longdouble'>, <class 'numpy.float64'>, <class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.intc'>, <class 'numpy.int64'>, <class 'numpy.timedelta64'>, <class 'numpy.datetime64'>, <class 'numpy.object_'>, <class 'numpy.bytes_'>, <class 'numpy.str_'>, <class 'numpy.uint8'>, <class 'numpy.uint16'>, <class 'numpy.uintc'>, <class 'numpy.uint32'>, <class 'numpy.uint64'>, <class 'numpy.void'>)
Column Vector:
 (4, 1)
Row Vector:
 [1 2 3 4]


In [7]:
#How do you calculate the mean of a NumPy array using the mean() function?

#### Calculating the mean of a NumPy array using the mean() function

For an array `arr`, the mean can be calculated using `np.mean(arr)`<br/>
If the array `arr_nan` with one or more _not a number_ (`np.nan`) values, the mean can be calculated using the **Nan**-aware function `np.nanmean(arr_nan)`. <br/>

Usage of `np.mean` is shown in the code block below:

In [8]:
# Creating the array, arr
arr = np.arange(10)

# Calculating mean of the array arr
arr_mean = np.mean(arr)

# Displaying the results
print("Array: ", arr)
print("Mean: ", arr_mean)

Array:  [0 1 2 3 4 5 6 7 8 9]
Mean:  4.5


In [9]:
#What is broadcasting in NumPy, and how can it be useful?

#### Broadcasting in Numpy

Broadcasting provides for the performance of arithmetic calculations between arrays of different shapes.

Rules:<br/>
- If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is *padded* with ones on its leading (left) side.
- If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

Use:
- It is used in centering arrays.
- It is used to plot two dimensional functions.

In [10]:
#How do you create a 2D array in NumPy using Python's built-in list of lists?

#### Creating a 2D array in NumPy using Python's built-in list of lists

To create a 2d array:
- A lists of lists nested to only depth 2 is needed.
- The list is then converted to a NumPy array using `np.array(List)`

The code block below show the process:

In [11]:
# Creating the list of lists nested to 2 depths.
list_2D = [[0,1],[1,1]]

# Converting the list to a NumPy 2D array
np_2D_arr = np.array(list_2D)

# Displaying the results
print("list of lists:  ", list_2D)
print("Numpy 2D array: ")
np_2D_arr

list of lists:   [[0, 1], [1, 1]]
Numpy 2D array: 


array([[0, 1],
       [1, 1]])

In [12]:
#How can you slice a NumPy array to extract a subarray?

#### Slicing a Numpy array to extract a subarray.

Use case:<br/>
For a one dimensional array arr;<br/>
`arr[[start]:[stop]:[step]]` is used where;
- `[start]` is an integer stating the index of the first element of the slice. Leaving this out defaults the `[start]` parameter to 0
- `[stop]` is an integer stating the index of the element after the last element to be sliced. Leaving this out defaults the `[stop]` parameter to the index of the last element in the array plus one.
- `[step]` indicates the count to the next index to include in the splice. It defaults to 1.

For multidimensional arrays, the multiple slices are separated by commas as; <br/>
For a 2-dimensional array, arr2D, the splices occurs as `arr2D[(row_splice_indices),(column_splice_indices)]` or `arr2D[(first_dimension_splice_indices),(second_dimension_splice_indices)`

The higher dimensional arrays follow the same rules as the two dimensional arrays.

Examples are shown in the code block below:

In [13]:
# For a one dimensional array
arr1D = np.array([0,1,2,3,4,5,6])

# Splicing out from second to fourth index(exclusive)
arr1D_splice = arr1D[2:4]

# For a two dimensional array
arr2D = np.array([[0,1,2,3,4,5,6],
                  [1,2,3,4,5,6,7],
                  [2,3,4,5,6,7,8],
                  [3,4,5,6,6,8,9]])

# Splicing out every other row and every other column in a two dimensional array
arr2D_splice = arr2D[::2,::2]

# Printing out the results
print("One dimensional array, arr1D:\n", arr1D)
print("Splice of one dimensional array(arr1D_splice): \n", arr1D_splice)
print("Two dimensional array, arr2D:\n", arr2D)
print("Splice of two dimensional array(arr2D_splice): \n", arr2D_splice)

One dimensional array, arr1D:
 [0 1 2 3 4 5 6]
Splice of one dimensional array(arr1D_splice): 
 [2 3]
Two dimensional array, arr2D:
 [[0 1 2 3 4 5 6]
 [1 2 3 4 5 6 7]
 [2 3 4 5 6 7 8]
 [3 4 5 6 6 8 9]]
Splice of two dimensional array(arr2D_splice): 
 [[0 2 4 6]
 [2 4 6 8]]


In [14]:
#What are some of the available functions for performing element-wise operations on NumPy arrays?

#### Available functions for performing element-wise operations on NumPy arrays

                        
`np.add`         
`np.subtract`<br/> 
`np.negative`<br/> 
`np.multiply`<br/> 
`np.divide`<br/> 
`np.floor_divide`<br/> 
`np.power`<br/> 
`np.mod`<br/>

In [15]:
#How do you reshape a NumPy array to have a different shape?

#### Reshaping a NumPy array to a different shape

The `reshape()` method is used to reshape while maintaining the size of both array as equal.

For `arr1D = np.array([0,1,2,3,4,5])`, `arr1D.reshape((2,3))` would change the 1 dimensional array to a 2 by 3 two dimensional array.

In [16]:
# Creating the array
arr1D = np.array([0,1,2,3,4,5])

# Reshaping the 1D array to a 2X3 array
arr1D_reshaped = arr1D.reshape((2,3))

# Printing out the results.
print("Original array:\n", arr1D)
print("Reshaped array:\n", arr1D_reshaped)

Original array:
 [0 1 2 3 4 5]
Reshaped array:
 [[0 1 2]
 [3 4 5]]


In [17]:
#How do you perform matrix multiplication on two NumPy arrays using the dot() function?

#### Using the NumPy dot() function for matrix multiplication

In [18]:
# Array defining
arr1 = [[1,2],[1,3]]
arr2 = [[2,3],[4,5]]

# Making the dot product
dot_pdt = np.dot(arr1,arr2)

#Printing output
print("Dot product of arr1 and arr2:\n", dot_pdt)

Dot product of arr1 and arr2:
 [[10 13]
 [14 18]]


In [19]:
#How can you use the where() function to apply a condition to a NumPy array?

#### Using the where() function to apply a condition to a NumPy array

The syntax is `numpy.where(condition, [x,y])` where condition is a relational that can give a bolean if applied to an array, x and y are values from which to choose. x, y and condition have to be follow the broadcasting rules if consideration is to be made.

Example is as in the code block below:

In [20]:
# Creating array
arr = np.arange(1,40,2)

# Using a mask to replace all values divisible by 3 by 0
arr_where = np.where(np.mod(arr,3)==0, 0, arr)

arr_where

array([ 1,  0,  5,  7,  0, 11, 13,  0, 17, 19,  0, 23, 25,  0, 29, 31,  0,
       35, 37,  0])

In [21]:
#What is the difference between the flatten() and ravel() functions in NumPy?

#### Difference between the flatten() and ravel() functions in NumPy

The `ravel()` and `flatten()`functions of NumPy returnsthe elements of the input as a one-dimensional array.

Difference:<br/>
`ravel()` returns a view of the original array wheres `flatten()` returns a copy. Hence modifying a value under the ravel function modifies the original array.


Examples are as in the code block below:

In [22]:
# defining the array
arr = np.array([[0,2,4],[6,8,10]])

# Using flatten() and changing element 2 to 99
arr_flat = arr.flatten()
arr_flat[arr_flat==2] = 99

print(arr_flat) # printing out the altered one
print(arr) # printing the original array

# Using ravel() and changing element 2 to 99
arr_rav = arr.ravel()
arr_rav[arr_rav==2] = 99

print(arr_rav) # printing out the altered one
print(arr) # printing the original array.Here the 2 in the original array is change to 99

[ 0 99  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]
[ 0 99  4  6  8 10]
[[ 0 99  4]
 [ 6  8 10]]


In [23]:
#How do you use NumPy's advanced indexing capabilities to select specific elements from an array?

#### Using NumPy's advanced indexing capabilities to select specific elements from an array.

In [24]:
# Defining the array.
arr = np.arange(1,40,2).reshape(4,5)

# Using advanced indexing to select all values divisible by 3
arr3 = arr[np.mod(arr,3)==0] # This uses the np.mod to find the remainder of the division of the values in array, arr by 3
# If the result of the division is zero, that value is returned and put into array, arr3

#printing out the elements selected
print("Elements of arr divisible by 3:\n",arr3)

Elements of arr divisible by 3:
 [ 3  9 15 21 27 33 39]


In [25]:
#How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

#### Using NumPy's broadcasting rules to perform operations on arrays with different shapes

In [26]:
# For two arrays with one having fewer dimensions
arr1 = np.array([1,2,3,4,5]) # One dimensional array (5,)
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]]) # Two dimensional array (2,5)

# Adding arr1 to arr 2 gives a 2 dimensional array (2,5)
arr2p1 = arr2 + arr2 # Here the arr1 is padded with ones to become shaped as (1,5) then the two are added

# For two arrays with one having one of the dimensions as 1
arr3 = np.array([[1,2,3,4,5]]) # One dimensional array (1,5)
arr4 = np.array([[1,2,3,4,5],[1,2,3,4,5]]) # Two dimensional array (2,5)

# Adding arr3 to arr 4 gives a 2 dimensional array (2,5)
arr4p3 = arr4 + arr3 # Here the arr3 has its dimension equal to 1 stretched to 2 making its shape (2,5) then the addition happend.

# For two arrays with diagreements in the dimensional sizes not met by the first two rules
arr5 = np.array([1,2,3,4,5]) # One dimensional array (5,)
arr6 = np.array([[1,2],[1,2],[1,2],[1,2]]) # Two dimensional array ,(4,2)

# Adding arr5 to arr6 gives an error
#arr6p5 = arr6 + arr5 # Here, the padding on arr5 makes it have shape (1,5), then stretched to become (4,5) making the shapes incopatible hence the error.


# printing out the the results
print("For two arrays with one having fewer dimensions (5,) and (2,5), sum is :\n", arr2p1)
print("For two arrays with one of the dimensions as 1 (1,5) and (2,5), sum is :\n", arr4p3)
print("For two arrays that with application of rules 1 and 2, the arrays stay incompatible (5,) and (4,2), an error is imminent as below :\n")
print(arr6 + arr5)

For two arrays with one having fewer dimensions (5,) and (2,5), sum is :
 [[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
For two arrays with one of the dimensions as 1 (1,5) and (2,5), sum is :
 [[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
For two arrays that with application of rules 1 and 2, the arrays stay incompatible (5,) and (4,2), an error is imminent as below :



ValueError: operands could not be broadcast together with shapes (4,2) (5,) 

In [27]:
#How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?

#### Performing element-wise division of two NumPy arrays while ignoring divide-by-zero errors

Here, we can use the `np.where` function masking out values less than zero.

Example is shown in the code block below:

In [28]:
# Array defining
a = 5
arr2 = np.array([0,2,3,4,5,0,2,3])

# Using the np.where function to divide arr1 by arr2
arr_div = np.where(arr2==0, a, a/arr2) # here whenever arr2 value is a zero, the value of a is retained as is.

arr_div

C:\Users\NDA\AppData\Local\Temp\ipykernel_9088\402943287.py:6: RuntimeWarning: divide by zero encountered in true_divide
  arr_div = np.where(arr2==0, a, a/arr2) # here whenever arr2 value is a zero, the value of a is retained as is.


array([5.        , 2.5       , 1.66666667, 1.25      , 1.        ,
       5.        , 2.5       , 1.66666667])

### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [29]:
def array_statistics_calculator(): # Defining the function for calculating array statistics
    # Using the input function to seek input from the user
    user_input = input("Enter a list of numbers separated by commas: ")
    
    # Converting the textual user input into a 1D NumPy array
    user_array = np.array([int(x) for x in user_input.split(",")])
    
    # Printing the summary statistics for the input array
    print("Statistics for the input array:")
    print("Mean: ", np.mean(user_array))
    print("Median: ", np.median(user_array))
    print("Standard Deviation: ", np.std(user_array))
    print("Maximum: ", np.max(user_array))
    print("Minimum: ", np.min(user_array))

# Invoking the program or function
array_statistics_calculator()

Enter a list of numbers separated by commas: 2,5,7,3,1,9
Statistics for the input array:
Mean:  4.5
Median:  4.0
Standard Deviation:  2.8136571693556887
Maximum:  9
Minimum:  1


#### Explanation for the function above

In `def array_statistics_calculator():`;
- `def` provides for the definition of a function.
- `array_statistics_calculator` is the name of the function.
- `()` holds the function's input parameters. If the function has no input parameters, it is left blank.
- `:` marks the end of the function definition and start of the function's body.

The body of the function should be indented. Removing this indention makes the code block not part of the function.

In the function's code block;
- `user_input = input("Enter a list of numbers separated by commas: ")` prompts the user to "Enter a list of numbers separated by commas" and stores the user input into the `user_input` variable. `input` in a built in variable that reads input from the user's input devices.
<br/>

- `user_array = np.array([int(x) for x in user_input.split(",")])` converts the value of `user_input` into a 1D NumPy array of integer values.
    - `split("delim")` function splits the value of the provided variable along delimeter `delim` which for this case is a comma (,) returning a list of values.
    - `[int(x) for x in user_input.split(",")]` is list comprehension that converts each value in the list returned by `user_input.split(",")` into an integer using the function `int()`. This returns a list of integer.
Finally, the returned list is converted to a NumPy array using the `array` function of NumPy.


The code block below prints the mean, median, standard deviation, maximum and minumum statistics of the NumPy array, `user_array` created; using functions np.mean, np.median, np.std, np.max, np.min respectively where np is an alias for numpy.

```
    print("Mean: ", np.mean(user_array))
    print("Median: ", np.median(user_array))
    print("Standard Deviation: ", np.std(user_array))
    print("Maximum: ", np.max(user_array))
    print("Minimum: ", np.min(user_array))
```