Numpy Assignment
Student Name: Kevin Cissy Nabukeera

Reg No: 2022/HD07/2047U
Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

What is NumPy, and what are some of its key features?

NumPy is a Numerical Python that provides an efficient interface to store and operate on dense data buffers.
Key Features of NumPy include; 
Linear algebra
Fourier transforms
Pseudorandom number generators
Mutlidimensional arrays

How do you create a NumPy array using Python's built-in range() function?

After importing NumPy as np, np.array is used to create an array.
To create a range of integers range() is used in np.array

In [15]:
#import NumPy
import numpy as np
# To create x as a range of 20 integers
x = np.array(range(20))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


What is the difference between a scalar value and a vector in NumPy?

A scalar value is a single value with no dimension while a vector is a one dimensional array of values

In [30]:
# An Example of a scalar value
Districts = np.array(10)
# An example of vector
No_districts = np.array([1,2,3,4,5,6,7,8,9,10])
print(Districts)
print(No_districts)

10
[ 1  2  3  4  5  6  7  8  9 10]


How do you calculate the mean of a NumPy array using the mean() function?

Using np.mean we can calculate the mean of a NumPy array. Here is an example

In [7]:
# import NumPy 
import numpy as np
# x is equal to integers in the range of 10
x = np.mean(range(10))
# calculate the mean of the values in the range(10)
print(x)

4.5


What is broadcasting in NumPy, and how can it be useful?

Broadcasting is the use of arrays with different shapes in arithmetic operations, without the need for explicit expansion or copying of the arrays. 
Broadcasting allows for efficient computations and simplifies the code, as it eliminates the need to manually align arrays with compatible shapes. For example arrays of different shapes can be added

In [8]:
import numpy as np
x = np.array([1,2])
y = np.array([[3],[4],[5]])
# x and y have different shapes and we want to create a variable z that contains both x any y
z = x + y
print(x)
print(y)
print(z)


[1 2]
[[3]
 [4]
 [5]]
[[4 5]
 [5 6]
 [6 7]]


How do you create a 2D array in NumPy using Python's built-in list of lists?

Use the list of lists in a NumPy array. 


In [9]:
import numpy as np
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


How can you slice a NumPy array to extract a subarray?

First creat an NumPy array that is dimensional, then slice it

In [10]:
import numpy as np
y = np.array([[1,2,3],[5,4,6]])
print(y)
# To slice
sub_array = y[:2, :2]
print(sub_array)


[[1 2 3]
 [5 4 6]]
[[1 2]
 [5 4]]


What are some of the available functions for performing element-wise operations on NumPy arrays?

numpy.add():  Adds corresponding elements in two arrays.
numpy.subtract():  Subtracts corresponding elements in two arrays.
numpy.multiply():  Multiplies corresponding elements in two arrays.
numpy.divide():  Divides corresponding elements in two arrays.
numpy.power():  Raises corresponding elements in an array to a specified power.
numpy.sqrt():  Computes the square root of each element in an array.
numpy.exp():  Computes the exponential of each element in an array.
numpy.log():  Computes the natural logarithm of each element in an array.

How do you reshape a NumPy array to have a different shape?

By using the reshape option to change the array to a dimension

In [11]:
x = np.arange(10).reshape((2,5))
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


How do you perform matrix multiplication on two NumPy arrays using the dot() function?

The dot() function  takes two matrices of the same shape and returns their matrix multiplication

In [12]:
x = np.array([[1,2],[3,5]])
y = np.array([[6,7],[8,9]])
# using the dot() function
z = np.dot(x, y)
z

array([[22, 25],
       [58, 66]])

How can you use the where() function to apply a condition to a NumPy array?

The where() function in NumPy is used to return an array with elements chosen from two input arrays based on a specified condition. It takes three arguments; the condition that specifies which elements to select from the input arrays, the array that is selected where the condition is True, and the array that is selected where the condition is False.

In [13]:
import numpy as np
x = np.array([1,2,3,4])
#Define the condition
condition = np.array([True, False,False, False])
# applying where()
result = np.where(condition,x, -2)
# The above replaces False with -2
print(result)


[ 1 -2 -2 -2]


What is the difference between the flatten() and ravel() functions in NumPy?

Both flatten() and ravel() functions in NumPy are used to flatten multi-dimensional arrays into one-dimensional arrays.
Flatten() always returns a copy of the input array.
Ravel() returns a view of the input array whenever possible

In [14]:
#Using the previous array
x = np.array([[1,2],[3,4]])
# flatten()
x_flattened = x.flatten()
#ravel()
x_ravelled = x.ravel()
# modify the x array
x[0, 0] = 5
print(x_flattened)
print(x_ravelled)

[1 2 3 4]
[5 2 3 4]


How do you use NumPy's advanced indexing capabilities to select specific elements from an array?

NumPy's advanced indexing capabilities allow you to select specific elements from an array by using arrays of indices or Boolean masks


In [15]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
# create an array of row indices
row_indices = np.array([0, 2])
# create an array of column indices
col_indices = np.array([1, 0])
# use advanced indexing to select specific elements
selected_specific_elements = x[row_indices, col_indices]
print(selected_specific_elements)

[2 5]


How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

Broadcasting on arrays with different shapes allows to perform element-wise operations. The broadcasting rules work by adding new dimensions to the smaller array until the shapes.

Broadcasting with arrays of different dimensions by adding dimensions of size 1 to the smaller array.

Broadcasting with scalar values to arrays of any shape

How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?

use the numpy.divide() function along with the numpy.errstate()

In [16]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([0, 1, 2, 3, 0])
# temporarily sets the behavior of NumPy's error handling system for the division operation to "ignore" any divide-by-zero
with np.errstate(divide='ignore', invalid='ignore'):
    z = np.divide(x, y)
print(z)

[       inf 2.         1.5        1.33333333        inf]


### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [21]:
import numpy as np
# Prompt the user to enter a list of numbers separated by commas
input_str = input("Enter a list of numbers separated by commas: ")
# Convert the input into a 1D NumPy array
nums = np.fromstring(input_str, dtype=int, sep=',')
# Calculate the mean of the numbers
mean = np.mean(nums)
# Calculate the median of the numbers
median = np.median(nums)
# Calculate the standard deviation of the numbers
std = np.std(nums)
# Calculate the maximum value of the numbers
max_val = np.max(nums)
# Calculate the minimum value of the numbers
min_val = np.min(nums)
# Display the statistics with appropriate labels
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std)
print("Maximum value: ", max_val)
print("Minimum value: ", min_val)

Mean:  3.5
Median:  3.5
Standard Deviation:  1.707825127659933
Maximum value:  6
Minimum value:  1
