##Numpy Assignment 1:

Student Name: Kizito Moses


Student RegNo:2022/HD07/1971U


In [4]:
#create numpy one dimentional array with 10 elements

import numpy as np
moz = np.array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])
print(moz)

[11 13 15 17 19 21 23 25 27 29]


In [5]:
# create an numpy array from a python list
fruit_list = ["apple", "banana", "cherry", "date", "elderberry"]

# Create a NumPy array from the list of fruits
string_array = np.array(fruit_list)

# Print the array
print(fruit_list)

['apple', 'banana', 'cherry', 'date', 'elderberry']


In [6]:
#create an array of five values evenly spaced between 0 and 1
my_arr = np.linspace(0, 1, 5)

print(my_arr)


[0.   0.25 0.5  0.75 1.  ]


In [7]:
#Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 3
moz_array = np.random.normal(loc=0, scale=3, size=(3,3))

# Print the array
print(moz_array)


[[-1.51985496  2.31998861 -3.54146991]
 [-5.41534498 -2.80124189 -2.30271354]
 [-0.75487396  0.08380716 -2.36459393]]


In [15]:
#creat a 5x5 array with complex numbers
size = 5

kizito = np.empty((size, size), dtype=np.complex128)

# Use a nested for loop to fill the array with complex numbers
for i in range(size):
    for j in range(size):
        # Generate a random complex number with real and imaginary parts between -1 and 1
        real = np.random.uniform(-1, 1)
        imag = np.random.uniform(-1, 1)
        comp = np.complex128(real + imag*1j)
        kizito[i][j] = comp

# Print the array
print(kizito)

[[ 0.75110747-0.65690222j -0.52242407-0.37702028j -0.65874435-0.59617534j
   0.76447274-0.06896397j  0.90968728-0.99730341j]
 [ 0.36281711+0.41021936j  0.9892113 +0.10992594j  0.63749938-0.38107762j
  -0.94838433+0.1336436j   0.48390289+0.57581965j]
 [-0.03816097+0.57205399j  0.47480041+0.72087204j -0.80718647+0.62771017j
  -0.67796864+0.65330307j  0.21570765+0.57364716j]
 [-0.67701096-0.95065067j  0.67743009+0.19544294j  0.21196717+0.20792989j
  -0.17451635+0.2520928j   0.79721521-0.47372466j]
 [-0.59800438-0.41831302j -0.82701918-0.3161906j  -0.75299038+0.91793925j
   0.32653856-0.22948789j  0.17732215-0.52114563j]]


In [18]:
#create a one dimentional array with 20 elements and return elements from 3 to 7
kztm = np.arange(20)

subset = kztm[3:8]

print(subset)


[3 4 5 6 7]


In [22]:
#create a 3x3 array of random integers and reverse elements of the first row
arr = np.random.randint(0, 10, size=(3, 3))

# Print the original array
print("Original array:")
print(arr)

# Reverse the first row of the array
arr[0] = arr[0, ::-1]

# Print the updated array
print("Updated array:")
print(arr)


Original array:
[[8 0 9]
 [8 2 6]
 [2 3 2]]
Updated array:
[[9 0 8]
 [8 2 6]
 [2 3 2]]


In [25]:
#create 2 4x4 arrays and stack them both vertically and horizontally

arr1 = np.random.randint(2, 13, size=(4, 4))
arr2 = np.random.randint(0, 12, size=(4, 4))

# Stack the arrays vertically
vertical_stack = np.vstack((arr1, arr2))

print(vertical_stack)

[[ 8 11  9 11]
 [ 4 10  6  2]
 [ 2  8  5 10]
 [11 12  7  7]
 [ 0  8  0  4]
 [ 0  7  0 10]
 [ 3 11  3  2]
 [11  0  7  1]]


In [ ]:
#what are the rules of numpy broadcasting?

#NumPy broadcasting allows arithmetic operations to be performed on arrays with different shapes and sizes. ton dimensions (i.e., dimensions of size 1) to the smaller array.

#When the size of any dimension in the input arrays does not match, the array with size 1 in that dimension is stretched to match the size of the other array.

#When the input arrays have different shapes, the array with fewer dimensions is broadcast to match the shape of the larger array by adding singleton dimensions to its shape.

#When broadcasting a scalar value to an array, the scalar value is treated as a zero-dimensional array and is broadcast to match the shape of the larger array by adding singleton dimensions.

#Broadcasting is not allowed if the dimensions of the arrays do not match or if the sizes of the arrays do not match in any dimension.

#If the arrays cannot be broadcast, a ValueError is raised.

In [ ]:
# create two 3X3 matrices that are incopatible and raise an error

mtx1 = np.array([[1, 2, 3], [4, 0, 6], [7, 2, 9]])
mtx2 = np.array([[0, 2], [3, 4], [7, 6]])

# Try to add the matrices
result = mtx1 + mtx2

# This will raise a ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [28]:
#create a 4x4 matrix with random integers and use a boolean mask to check for those above 4

import numpy as np

# Create a 4x4 matrix of random integers between 0 and 9
matrix = np.random.randint(-2, 11, size=(4, 4))
print(matrix)

# Create a boolean mask to check for values above 4
mask = matrix > 4
print(mask)

# Use the boolean mask to get the values above 4
values_above_4 = matrix[mask]
print(values_above_4)


[[ 7  9  7 -2]
 [-1  8  3  1]
 [ 3  6 -2 -1]
 [ 6 -1 -2 10]]
[[ True  True  True False]
 [False  True False False]
 [False  True False False]
 [ True False False  True]]
[ 7  9  7  8  6  6 10]
