## Numpy Assignment
- Student Name: KISAKYE BARBRA

- Reg No:2022/HD07/1966U
- STDNO:2200701966

## Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

### What is NumPy, and what are some of its key features?
NumPy is a Python library for numerical computing that provides efficient data structures for working with multi-dimensional arrays and matrices, as well as a collection of mathematical functions to manipulate those arrays. NumPy stands for Numerical Python.

Features
Multidimensional arrays: NumPy provides a powerful N-dimensional array object that can hold homogeneous data, which allows for efficient computation on large amounts of data.

Broadcasting: NumPy's broadcasting feature allows for element-wise operations between arrays with different shapes and sizes, making it easy to perform operations on entire arrays without using loops.

Mathematical functions: NumPy provides a wide range of mathematical functions that can be applied element-wise to arrays, including functions for trigonometry, logarithms, exponents, and more.

Linear algebra: NumPy provides a suite of linear algebra functions, including matrix 



## How do you create a NumPy array using Python's built-in range() function?
You can create a NumPy array using Python's built-in range() function by first creating a Python list using range() and then converting it to a NumPy array using the numpy.array() function. 

In [ ]:
import numpy as np

# Create a Python list using the range() function
my_list = list(range(5))

# Convert the Python list to a NumPy array
my_array = np.array(my_list)

print(my_array)
# Output: [0 1 2 3 4]

### What is the difference between a scalar value and a vector in NumPy?

In NumPy, a scalar value is a single numerical value, while a vector is a one-dimensional array of numerical values.

A scalar value in NumPy is represented as a single element with no dimensions.

A vector in NumPy is an array of numerical values with a single dimension

In [ ]:
import numpy as np
#example for a Scalar in NumPy
x = np.array(5)
print(x)
# Output: 5

print(x.shape)
# Output: ()

# example for vector in NumPy
import numpy as np

y = np.array([1, 2, 3, 4])
print(y)
# Output: [1 2 3 4]

print(y.shape)
# Output: (4,)


### How do you calculate the mean of a NumPy array using the mean() function?
To calculate the mean of a NumPy array using the mean() function, you can follow these steps:

Import the NumPy library
Create a NumPy array
Call the mean() function on the array
The mean() function will return the average (mean) of all the elements in the array

In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
my_mean = np.mean(my_array)

### What is broadcasting in NumPy, and how can it be useful?

In NumPy, broadcasting is a technique that allows for element-wise operations between arrays of different shapes and sizes, without the need to explicitly reshape or replicate the arrays.

More specifically, broadcasting involves a set of rules that determine how arrays with different shapes can be used in arithmetic operations. These rules apply whenever arrays are of different shapes, but are compatible in some way.


In [ ]:
import numpy as np

# Creating two arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Broadcasting the two arrays
result = x + y

# Displaying the result
print(result)

### How do you create a 2D array in NumPy using Python's built-in list of lists?
First you  import Numpy Library and the you can use the numpy.array() function and pass in the list of lists as an argument.

In [ ]:
import numpy as np

# create a list of lists
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# create a 2D NumPy array from the list of lists
my_array = np.array(my_list)

# print the array
print(my_array)

### How can you slice a NumPy array to extract a subarray?
To slice a NumPy array and extract a subarray, you can use indexing notation with a colon (:) to indicate the start and end points of the slice.The syntax for slicing a NumPy array is array[start_row:end_row, start_col:end_col].



In [ ]:
import numpy as np

# create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# slice the array to extract a subarray
subarr = arr[1:3, 1:3]

print(subarr)

### What are some of the available functions for performing element-wise operations on NumPy arrays?
- np.add(): Adds two arrays element-wise.
- np.subtract(): Subtracts two arrays element-wise.
- np.multiply(): Multiplies two arrays element-wise.
- np.divide(): Divides two arrays element-wise.
- np.power(): Calculates the exponent of an array element-wise.
- np.sqrt(): Calculates the square root of an array element-wise.
- np.exp(): Calculates the exponential of an array element-wise.
- np.log(): Calculates the natural logarithm of an array element-wise.
- np.sin(): Calculates the sine of an array element-wise.
- np.cos(): Calculates the cosine of an array element-wise.
- np.tan(): Calculates the tangent of an array element-wise.
- np.arcsin(): Calculates the inverse sine of an array element-wise.

### How do you reshape a NumPy array to have a different shape?
To reshape a NumPy array, you can use the reshape() method of the NumPy array. This method takes in a new shape as a tuple and returns a new array with the specified shape.

In [6]:
import numpy as np

# Create a NumPy array with shape (3, 4)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Reshape the array to have shape (4, 3)
new_arr = arr.reshape((4, 3))

print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### How do you perform matrix multiplication on two NumPy arrays using the dot() function?
You can perform matrix multiplication on two NumPy arrays using the dot() function. Forexample

In [7]:
import numpy as np

# Create two NumPy arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using dot() function
C = A.dot(B)

print(C)

[[19 22]
 [43 50]]


### How can you use the where() function to apply a condition to a NumPy array?
The where() function in NumPy is used to apply a condition to a NumPy array, and returns a new array containing elements from one of two arrays, depending on whether the condition is True or False. The general syntax for using the where() function is:
numpy.where(condition, x, y)

In [8]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4,5,6])

# Use where() to filter the array for values greater than 3
new_arr = np.where(arr > 3)

# Print the filtered array
print(new_arr)

(array([3, 4, 5], dtype=int64),)


### What is the difference between the flatten() and ravel() functions in NumPy?
Both flatten() and ravel() functions in NumPy are used to convert a multi-dimensional array into a one-dimensional array, but they have some differences.

flatten() creates a copy of the original array, whereas ravel() returns a view of the original array. This means that changes made to the flattened array returned by flatten() will not affect the original array, while changes made to the array returned by ravel() will affect the original array.

Additionally, ravel() may return a reference to the original array in some cases, rather than a copy or view, depending on the memory layout of the original array. In contrast, flatten() always returns a copy of the original array.

In [10]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
# original array:
# [[1 2]
#  [3 4]]

flattened = arr.flatten()
flattened[0] = 0
# flattened array:
# [0 2 3 4]

print(arr)
# original array is not affected:
# [[1 2]
#  [3 4]]

raveled = arr.ravel()
raveled[0] = 0
# raveled array:
# [0 2 3 4]

print(arr)
# original array is affected:
# [[0 2]
#  [3 4]]

[[1 2]
 [3 4]]
[[0 2]
 [3 4]]


#### How do you use NumPy's advanced indexing capabilities to select specific elements from an array?
NumPy's advanced indexing is a way to select specific elements or groups of elements from an array by using an index or boolean mask array. Here's how you can use it:
Using a single index array:
You can use a single index array to select specific elements from an array. For example:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
index = np.array([1, 3])

selected = arr[index]
print(selected)  # Output: [2 4]

[2 4]


Using multiple index arrays:
You can also use multiple index arrays to select elements from an array. For example:

In [3]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
row_index = np.array([0, 2])
col_index = np.array([1, 0])

selected = arr[row_index, col_index]
print(selected)  # Output: [2 5]

[2 5]


#### How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

NumPy's broadcasting rules allow you to perform operations on arrays with different shapes. Broadcasting is a powerful tool that allows NumPy to work with arrays of different shapes and sizes. It enables you to perform operations on arrays without explicitly creating copies of the data.

The basic idea behind broadcasting is that if two arrays have different shapes, but their dimensions match in some way, you can use them together in an operation. When performing an operation on two arrays, NumPy compares their shapes element-wise. If the dimensions of the arrays are not the same, but they are compatible according to the broadcasting rules, NumPy will broadcast one or both of the arrays to match the dimensions of the other

### How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?

You can perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors using the numpy.divide() function along with the numpy.errstate() context manager.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([0, 2, 0])

# Create a context manager to ignore divide-by-zero errors
with np.errstate(divide='ignore', invalid='ignore'):
    c = np.divide(a, b)

print(c)

[inf  1. inf]


###### Project: Array Statistics Calculator
**Description:**

#### In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

#### **Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [5]:
import numpy as np
# Prompt the user to enter a list of numbers separated by commas
input_str = input("Enter a list of numbers separated by commas: ")
# Convert the input into a 1D NumPy array
nums = np.fromstring(input_str, dtype=int, sep=',')
# Calculate the mean of the numbers
mean = np.mean(nums)
# Calculate the median of the numbers
median = np.median(nums)
# Calculate the standard deviation of the numbers
std = np.std(nums)
# Calculate the maximum value of the numbers
max_val = np.max(nums)
# Calculate the minimum value of the numbers
min_val = np.min(nums)
# Display the statistics with appropriate labels
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std)
print("Maximum value: ", max_val)
print("Minimum value: ", min_val)

Mean:  2.0
Median:  2.0
Standard Deviation:  0.816496580927726
Maximum value:  3
Minimum value:  1
