## Numpy Assignment
Student Name:OKELLO ISAAC OPIO

Reg No:2022/HD07/2052U

## Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

#  What is NumPy, and what are some of its key features?

## NumPy is a Python library that provides support for multidimensional arrays and matrices along with a vast collection of mathematical functions to operate on them. 
## key features of NumPy:

### - Can have multiple dinemnsions of arrays or matrices
### - NumPy can be integrated with other Python libraries, such as Pandas and Matplotlib.
### - NumPy is designed for efficient array operations and is optimized for both memory usage and speed.
### - NumPy provides a large collection of high-level mathematical functions, including basic arithmetic, linear algebra, Fourier transforms, and more.
### - NumPy arrays are homogeneous arrays, which means they can only contain elements of the same data type.

In [3]:
# How do you create a NumPy array using Python's built-in range() function?
import numpy as np

# Create a NumPy array using range function
my_range = range(0, 10, 2) # start=0, stop=10, step=2
my_array = np.array(my_range)

# Print the NumPy array
print(my_array)


[0 2 4 6 8]


In the above example, I create a range() object with a start value of 0, stop value of 10 (exclusive), and step value of 2. Then, we pass the range() object to the numpy.array() function to create a NumPy array. Finally, we print the resulting array using the print() function.

# What is the difference between a scalar value and a vector in NumPy?

### A scalar is a single value that can be represented by a NumPy array of dimension 0, while vector, is an array of numbers that has more than one value and can be represented by a NumPy array of dimension 1.

### Here are some examples to illustrate the difference between a scalar and a vector in NumPy:

In [4]:
# Scalar
# A scalar in NumPy is represented by an array with a shape of (), i.e., an array with zero dimensions.

import numpy as np

# Scalar value in NumPy
scalar = np.array(5)
print(scalar)

# Shape of scalar array
print(scalar.shape)



5
()


In [5]:
# Vector
# A vector in NumPy is represented by an array with a shape of (n,), where n is the number of elements in the vector.

import numpy as np

# Vector in NumPy
vector = np.array([1, 2, 3, 4, 5])
print(vector)

# Shape of vector array
print(vector.shape)



[1 2 3 4 5]
(5,)


# How do you calculate the mean of a NumPy array using the mean() function?

#### To calculate the mean of a NumPy array using the mean() function, we can simply pass the array as an argument to the function. The mean() function returns the arithmetic mean of the array elements.

#### Here's an example:

In [8]:
# In the above example, we first create a NumPy array arr with the values [1, 2, 3, 4, 5]. 
# We then call the mean() function on this array and assign the result to the variable mean. 
#Finally, we print the value of mean, which is the arithmetic mean of the array elements, i.e., 3.0.


import numpy as np

arrarr = np.array([1, 5, 7, 9, 10])
mean = np.mean(arrarr)

print(mean) 


6.4


# What is broadcasting in NumPy, and how can it be useful?


### Broadcasting is the ability of NumPy to perform operations on arrays with different shapes, by implicitly replicating the values of the smaller array to match the shape of the larger array. This allows for efficient computation without the need to create new arrays to match shapes.


In [9]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([1, 2, 3, 4])

C = A + B

print(C)


[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In the above code snippet, we first create a 2-dimensional NumPy array A with 3 rows and 4 columns using the numpy.array() function. Each row of the array contains 4 integers. Next, we create a 1-dimensional NumPy array B with 4 integers using the same numpy.array() function.

Then, we perform an arithmetic operation between the 2 arrays using the + operator. Since the + operator in NumPy performs element-wise addition between arrays, the operation is performed between B and each row of A. Specifically, the first element of B is added to the first element of each row of A, the second element of B is added to the second element of each row of A, and so on.

The resulting array C is also a 2-dimensional NumPy array with 3 rows and 4 columns, where each element is the sum of the corresponding elements of A and B.

Finally, we print the resulting array C using the print() function.

# How do you create a 2D array in NumPy using Python's built-in list of lists?

#### To create a 2D NumPy array using Python's built-in list of lists, you can pass the list to the numpy.array() constructor as shown below:

In [10]:
# In this example, my_list is a list of lists containing the values for the 2D array, 
# and my_array is a NumPy array created from my_list. The resulting NumPy array has shape (3, 3) 
# and contains the same values as the original list of lists.

import numpy as np

my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_array = np.array(my_list)

print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# How can you slice a NumPy array to extract a subarray?

### To slice a NumPy array and extract a subarray, you can use the indexing operator [] with the slice notation :. Here is an example:

In [11]:
import numpy as np

# create a NumPy array with 5 rows and 3 columns
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15]])

# extract a subarray with the first 3 rows and 2 columns
subarray = a[:3, :2]

print(subarray)


[[1 2]
 [4 5]
 [7 8]]


# What are some of the available functions for performing element-wise operations on NumPy arrays?

### 1. np.add(): This function is used to add two arrays element-wise.


In [14]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.add(arr1, arr2)

print(result) 

[5 7 9]


### 2. np.subtract(): This function is used to subtract two arrays element-wise.


In [15]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([4, 5, 6])

result = np.subtract(arr1, arr2)

print(result) 

[ 6 15 24]


### 3. np.multiply(): This function is used to multiply two arrays element-wise.

In [16]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.multiply(arr1, arr2)

print(result) 

[ 4 10 18]


### 4.np.divide(): This function is used to divide two arrays element-wise.

In [17]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 5, 3])

result = np.divide(arr1, arr2)

print(result) 

[ 5.  4. 10.]


### 5. np.power(): This function is used to raise the elements of an array to a given power element-wise.

In [18]:
import numpy as np

arr = np.array([1, 2, 3])

result = np.power(arr, 3)

print(result) 

[ 1  8 27]


### 6. np.sqrt(): This function is used to compute the square root of each element of an array.

In [19]:
import numpy as np

arr = np.array([4, 9, 16])

result = np.sqrt(arr)

print(result) 

[2. 3. 4.]


### 7. np.exp(): This function is used to compute the exponential of each element of an array.

In [20]:
import numpy as np

arr = np.array([1, 2, 3])

result = np.exp(arr)

print(result) 

[ 2.71828183  7.3890561  20.08553692]


### 8. np.log(): This function is used to compute the natural logarithm of each element of an array.

In [21]:
import numpy as np

arr = np.array([1, 2, 3])

result = np.log(arr)

print(result) 

[0.         0.69314718 1.09861229]


# How do you reshape a NumPy array to have a different shape?

### In NumPy, we can use the reshape() function to change the shape of an array without changing its data. The reshape() function returns a new array with the same data but with a different shape.
Example:

In [12]:
import numpy as np

# Create a 1-dimensional array with 6 elements
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2-dimensional array with 2 rows and 3 columns
arr2d = arr1d.reshape((2, 3))

print(arr2d)

# Reshape the array to a 3-dimensional array with 2 rows, 1 column, and 3 depth
arr3d = arr1d.reshape((2, 1, 3))

print(arr3d)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


# How do you perform matrix multiplication on two NumPy arrays using the dot() function?

### In NumPy, we can use the dot() function to perform matrix multiplication on two arrays. The dot() function computes the dot product of two arrays, which is equivalent to matrix multiplication for 2D arrays.

### The dot() function takes two arguments: the two arrays that you want to multiply. The function returns a new array that represents the result of the matrix multiplication.
Example:

In [13]:
import numpy as np

# In this example, we create two 2D arrays A and B, and then we compute their dot product using the dot() function.
# The result is a new 2D array C that represents the matrix multiplication of A and B.

# Create two 2D arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the dot product of A and B
C = np.dot(A, B)

print(C)

[[19 22]
 [43 50]]


# How can you use the where() function to apply a condition to a NumPy array?

### NumPy's where() function can be used to apply a condition to a NumPy array and create a new array by selecting values from two input arrays based on the given condition.

### The general syntax for the where() function is:

### numpy.where(condition, x, y)

### where condition is the boolean condition to be checked, x is the array containing the values to be selected where the condition is True, and y is the array containing the values to be selected where the condition is False.

Example:

In [24]:
import numpy as np

# create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# create a new array by selecting only even values from arr
new_arr = np.where(arr % 2 == 0, arr, 0)

print(new_arr)  

[0 2 0 4 0]


# What is the difference between the flatten() and ravel() functions in NumPy?

### Both flatten() and ravel() are NumPy functions used to convert multi-dimensional arrays into one-dimensional arrays, but there is a subtle difference between them.

### flatten() creates a copy of the original array, while ravel() returns a view of the original array whenever possible. A view is a reference to the same memory location as the original array, whereas a copy creates a new memory location with the same data.

### Here are some examples to illustrate the difference:

In [14]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Use flatten()
arr_flatten = arr_2d.flatten()
print(arr_flatten)

# Modify the flattened array
arr_flatten[0] = 7

# Verify that the original array is unchanged
print(arr_2d)

# Use ravel()
arr_ravel = arr_2d.ravel()
print(arr_ravel)

# Modify the raveled array
arr_ravel[0] = 7

# Verify that the original array is also modified
print(arr_2d)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[7 2 3]
 [4 5 6]]


### In the example above, flatten() creates a new array arr_flatten with the same data as the original array arr_2d. When we modify arr_flatten, the original array arr_2d is unchanged.

### On the other hand, ravel() returns a view of the original array arr_2d as a one-dimensional array arr_ravel. When we modify arr_ravel, the original array arr_2d is also modified, since they reference the same memory location.

### In summary, use flatten() if you want to ensure that the original array remains unchanged, and use ravel() if you want to modify the original array.

# How do you use NumPy's advanced indexing capabilities to select specific elements from an array?

### NumPy's advanced indexing allows you to select specific elements from an array based on a set of indices or a Boolean mask. Here are some examples of how to use advanced indexing to select elements from an array:

### 1. Indexing with integers: You can use an array of integers to select specific elements from another array. For example:

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])

selected_elements = arr[indices]

print(selected_elements) 

[1 3 5]


### 2. Indexing with Booleans: You can also use a Boolean mask to select elements from an array. The mask should have the same shape as the array and its values should be True or False. Only the elements with True values will be selected. For example:

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])

selected_elements = arr[mask]

print(selected_elements) 

[1 3 5]


### 3.Indexing with arrays of integers and Booleans: You can combine arrays of integers and Booleans to select elements from an array. In this case, the integers are used as indices to select elements from the array, and the Booleans are used as a mask to select elements from the resulting array. For example:

In [28]:
import numpy as np

# create an array
a = np.array([1, 2, 3, 4, 5])

# create an array of integers
indices = np.array([0, 2, 4])

# use the integers as indices to select elements
b = a[indices]  # returns [1, 3, 5]

# create an array of Booleans
mask = np.array([True, False, True, False, True])

# use the Boolean mask to select elements
c = a[mask]  
print(c)

[1 3 5]


# How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

#### NumPy's broadcasting rules allow for arithmetic operations to be performed on arrays with different shapes. The idea behind broadcasting is to stretch (or duplicate) arrays with smaller shape to match the shape of the larger arrays in a way that allows element-wise operations to be performed.

#### The broadcasting rules work as follows:

#### 1. If two arrays have different numbers of dimensions, the smaller array is padded with ones on its left side until it has the same number of dimensions as the larger array.

#### 2. If the shape of two arrays does not match along any dimension, the array with shape equal to 1 along that dimension is stretched to match the shape of the other array.

#### 3. If neither array has shape equal to 1 along a dimension, a "broadcast error" is raised.

#### For example, consider the following two arrays:


In [29]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

# The shapes of these arrays are (3,) and (3, 1), respectively. 
# Since b has an additional dimension with length 1, it is broadcasted to match the shape of a, resulting in the following broadcasted arrays:

a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[4, 4, 4], [5, 5, 5], [6, 6, 6]])

# Now, we can perform arithmetic operations on these broadcasted arrays as if they had the same shape. For example:

c = a + b

print(c)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


# How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?

#### To perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors, you can use the numpy.divide() function along with the numpy.seterr() function to suppress the divide-by-zero warning.

#### Here's an example:

In [16]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([0, 2, 0, 4])

# Suppress divide-by-zero warning
np.seterr(divide='ignore', invalid='ignore')

# Perform element-wise division while ignoring divide-by-zero errors
c = np.divide(a, b)

print(c)

[inf  1. inf  1.]


In this example, the numpy.seterr() function is used to suppress the divide-by-zero warning.
The divide argument specifies how to handle divide-by-zero errors, and the ignore value tells NumPy to ignore these errors. 
The invalid argument specifies how to handle invalid floating-point results (such as NaN or infinity), and the ignore value tells NumPy to ignore these as well.

The output above contains inf (infinity) values, which indicate that division by zero occurred. 
In this example, the first and third elements of the resulting array c are infinity because division by zero occurred in those positions. 
The second and fourth elements are 1.0 because there was no division by zero in those positions.

### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [18]:
import numpy as np

# Prompt user to enter list of numbers
num_list = input("Enter a list of numbers separated by commas: ")

# Convert input to NumPy array
num_array = np.array(num_list.split(','), dtype=float)

# Calculate statistics
mean = np.mean(num_array)
median = np.median(num_array)
std_dev = np.std(num_array)
max_val = np.max(num_array)
min_val = np.min(num_array)

# Display statistics
print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std_dev)
print("Maximum value:", max_val)
print("Minimum value:", min_val)


Mean: 4.75
Median: 5.0
Standard deviation: 1.0897247358851685
Maximum value: 6.0
Minimum value: 3.0
