# MSB7211 Big Bio-data analysis assignment
#### Student name: Yiga Fahim
#### Reg No: 2022/HD07/2054U
#### Date: 29-MAR-2023







### **Qn1**. What is NumPy, and what are some of its key features?

### **Ans.** 
NumPy (Numerical Python) is a popular Python library that provides support for numerical operations on multi-dimensional arrays and matrices. It is used for scientific computing, data analysis, and machine learning applications.

### Key features
1. Multi-dimensional arrays: NumPy provides a powerful and efficient array object, called ndarray, which can be used to store and manipulate multi-dimensional data. Ndarrays can be used to represent vectors, matrices, and tensors of various dimensions.

2. Broadcasting: NumPy allows for element-wise operations between arrays of different shapes and sizes, by automatically broadcasting the smaller array to match the shape of the larger array.

3. Vectorized operations: NumPy provides a set of functions that can be applied to entire arrays or selected elements, without the need for explicit looping.

4. Mathematical functions: NumPy includes a wide range of mathematical functions, including trigonometric, logarithmic, and exponential functions, as well as functions for linear algebra and Fourier analysis.

5. Performance: NumPy is optimized for performance, with most of its functions implemented in C or Fortran, which allows for efficient processing of large amounts of data.

6. Integration with other libraries: NumPy can be easily integrated with other Python libraries, such as Pandas, Matplotlib, and Scikit-learn, which makes it a powerful tool for data analysis and machine learning applications.

### **Qn2**. How do you create a NumPy array using Python's built-in range() function?
### **Ans**.

In [3]:
#loading the package
import numpy as np

# create a range object
my_range = range(10)

# convert the range object to a NumPy array
my_array = np.array(my_range)

# print the NumPy array
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


### **Qn3**. What is the difference between a scalar value and a vector in NumPy?
### **Ans**.
A scalar value is a single numerical value, such as an integer or a floating-point number, that is represented as a 0-dimensional NumPy array. A scalar value can be created using the np.array() function and passing in a single numerical value while a vector is a 1-dimensional array that represents a list of numerical values. A vector can be created using the np.array() function and passing in a list or tuple of numerical values. The main difference between a scalar value and a vector in NumPy is that a scalar is a 0-dimensional array that represents a single numerical value, while a vector is a 1-dimensional array that represents a list of numerical values.

#### Scalar value

In [32]:
# create a scalar value
my_scalar = np.array(5)

# print the scalar value and its shape
print(my_scalar)
print(my_scalar.shape)

5
()


#### Vector

In [33]:
# create a vector
my_vector = np.array([1, 2, 3])

# print the vector and its shape
print(my_vector)
print(my_vector.shape)

[1 2 3]
(3,)


### **Qn4**. How do you calculate the mean of a NumPy array using the mean() function?
### **Ans**.

In [34]:
# create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# To calculate the mean of the array
my_mean = np.mean(my_array)

# print the mean
print(my_mean)

3.0


### **Qn5**. What is broadcasting in NumPy, and how can it be useful?
### **Ans**.
Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays with different shapes and sizes. Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes by extending or "broadcasting" one or more of the arrays to match the shape of the other array(s) involved in the operation. This means that you can perform arithmetic, logical, and other operations on arrays of different shapes and sizes, without having to manually reshape or duplicate arrays.

Broadcasting follow these basic rules; If the arrays have different numbers of dimensions, the smaller array is broadcasted to the shape of the larger array by adding dimensions of size 1 at the beginning or end of the smaller array, If the arrays have the same number of dimensions, but their sizes do not match along a particular dimension, the array with size 1 is broadcasted along that dimension to match the size of the other array, If the first 2 two rules cant apply, a ValueError is raised.

Broadcasting can be useful in, performing element-wise operations on arrays with different shapes and sizes, adding a scalar value to an array, acaling an array by a scalar value, applying a function to an array element-wise, where the function takes a scalar argument.


##### foreaxmple

In [35]:
# create two arrays with different shapes
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])

# add the arrays using broadcasting
z = x + y

# print the result
print(z)

[[11 22 33]
 [14 25 36]]


Here allows us to perform the element-wise addition of x and y, even though they have different shapes. Broadcasting makes it possible to write more concise and readable code, without having to manually reshape or duplicate arrays.

### **Qn6**. How do you create a 2D array in NumPy using Python's built-in list of lists?
### **Ans**. 
Using the **np.array() ** function

In [36]:
# create a list of lists
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# create a 2D array from the list of lists
my_array = np.array(my_list)

# print the array
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Or

In [39]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### **Qn7**. How can you slice a NumPy array to extract a subarray?
### **Ans**. 
You can slice a NumPy array to extract a subarray using the indexing notation array[start:stop:step], where start is the index of the first element of the subarray, stop is the index of the last element plus one, and step is the stride between the elements. If any of these values are not specified, they default to the following:

--'start': 0

--'stop': size of the corresponding dimension

--'step': 1

##### foreaxmple

In [41]:
#create a 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# extract a subarray using slicing
sub_array = my_array[0:2, 1:3]

# print the subarray
print(sub_array)

[[2 3]
 [5 6]]


### **Qn8**. What are some of the available functions for performing element-wise operations on NumPy arrays?
### **Ans**. 

--'np.add()': element-wise addition of two arrays.

--'np.subtract()': element-wise subtraction of two arrays.

--'np.multiply()': element-wise multiplication of two arrays.

--'np.divide()': element-wise division of two arrays.

--'np.power()': element-wise exponentiation of an array to a given power.

--'np.sqrt()': element-wise square root of an array.

--'np.exp()': element-wise exponential function of an array.

--'np.log()': element-wise natural logarithm of an array.

--'np.abs()': element-wise absolute value of an array.

--'np.sin()': element-wise sine of an array.

### **Qn9**. How do you reshape a NumPy array to have a different shape?
### **Ans**. 
You can reshape a NumPy array to have a different shape using the 'reshape()' function. 

**Syntax-** new_array = old_array.reshape(new_shape)

##### foreaxmple

In [43]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [44]:
new_array = my_array.reshape((3, 2))
print(new_array)

[[1 2]
 [3 4]
 [5 6]]


### **Qn10**. How do you perform matrix multiplication on two NumPy arrays using the dot() function?
### **Ans**. 
**Syntax**- result = np.dot(array1, array2)

##### for example

In [48]:
array1 = np.array([[1, 2], [3, 4], [5, 6]])
array2 = np.array([[7, 8], [9, 10]])
result = np.dot(array1, array2)
print(result)

[[ 25  28]
 [ 57  64]
 [ 89 100]]


### **Qn11**. How can you use the where() function to apply a condition to a NumPy array?
### **Ans**. 
**Syntax**- result = np.where(condition, x, y)

##### forexample

In [50]:
my_array = np.array([1, 2, 3, 4, 5])
result = np.where(my_array % 2 == 0, my_array, -1)
print(result)

[-1  2 -1  4 -1]


Here We create a new array that contains only the even numbers in 'my_array', and replace the odd numbers with -1
The condition is 'my_array % 2 == 0', which returns a boolean array with 'True' where the corresponding element in 'my_array' is even, and 'False' where it is odd. 'x is my_array', which means that if condition is 'True', the corresponding element in the result will be the corresponding element in 'my_array'. 'y' is '-1', which means that if condition is 'False', the corresponding element in the result will be '-1'.

### **Qn12**. What is the difference between the flatten() and ravel() functions in NumPy?
### **Ans**. 
Both flatten() and ravel() functions in NumPy are used to convert a multidimensional array into a one-dimensional array exept the ravel() function returns a flattened array that shares the same memory as the original array. That is, if you modify the values of the flattened array, it will also modify the original array. On the other hand, the flatten() function always returns a new copy of the array, even if the original array was already one-dimensional.

**syntax for ravel() function**- flattened_array = np.ravel(original_array)
**syntax for flatten() function**- flattened_array = original_array.flatten()

##### for example

In [51]:
# Create a 2D array
original_array = np.array([[1, 2], [3, 4]])

# Use ravel()
flattened_array_ravel = np.ravel(original_array)
flattened_array_ravel[0] = 5

# Use flatten()
flattened_array_flatten = original_array.flatten()
flattened_array_flatten[1] = 6

print(original_array)
print(flattened_array_ravel)
print(flattened_array_flatten)

[[5 2]
 [3 4]]
[5 2 3 4]
[5 6 3 4]


### **Qn13**. How do you use NumPy's advanced indexing capabilities to select specific elements from an array?
### **Ans**. 

##### for example

1. Selecting elements with a list of indices:

In [53]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Select elements with indices 1 and 3
selected = arr[[1, 3]]

print(selected)

[2 4]


2. Selecting elements based on a Boolean mask:

In [54]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Create a Boolean mask
mask = np.array([True, False, True, False, True])

# Select elements based on the mask
selected = arr[mask]

print(selected)

[1 3 5]


3. Selecting elements from a 2D array using an index array for each dimension

In [55]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create index arrays for each dimension
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])

# Select elements based on the index arrays
selected = arr[row_indices, col_indices]

print(selected)

[2 9]


### **Qn14**. How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?
### **Ans**. 
NumPy's broadcasting rules allow you to perform operations on arrays with different shapes. Broadcasting is a set of rules that describes how arrays with different shapes can be used in arithmetic operations. The rules allow NumPy to perform element-wise operations on arrays with different shapes by implicitly expanding the smaller array to match the shape of the larger array.

**Examples of how to use broadcasting in NumPy:**

1. **Broadcasting a scalar value to an array**: The scalar value 2 will be broadcasted to match the shape of arr1, which has 3 elements.

In [56]:
# Create a 1D array
arr1 = np.array([1, 2, 3])

# Multiply each element of arr1 by 2
result = arr1 * 2

print(result)

[2 4 6]


2. **Broadcasting a smaller array to a larger array**: arr2 will be broadcasted to match the shape of arr1. arr2 is treated as if it were reshaped to [[10, 20], [10, 20], [10, 20]].

In [4]:
# Create a 2D array
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([10, 20])

# Add arr2 to each row of arr1
result = arr1 + arr2

print(result)

[[11 22]
 [13 24]
 [15 26]]


3. **Broadcasting two arrays with different shapes**: I will add arr2 to each column of arr1. I will use the np.newaxis to add a new axis to arr2, so that it could be broadcasted to match the shape of arr1

In [5]:
# Create a 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([10, 20, 30])

# Add arr2 to each column of arr1
result = arr1 + arr2[:, np.newaxis]

print(result)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


### **Qn15**. How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?
### **Ans**
To perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors, you can use the numpy.errstate context manager to temporarily ignore divide-by-zero errors, and then use the division operator / or the numpy.divide function.

##### for example

In [6]:
# Create two arrays
a = np.array([1, 2, 3, 0, 5])
b = np.array([0, 1, 2, 3, 0])

# Use errstate to ignore divide-by-zero errors
with np.errstate(divide='ignore', invalid='ignore'):
    c = np.divide(a, b)

print(c)

[inf 2.  1.5 0.  inf]


In this example, I have created two arrays a and b, and then used the numpy.divide function to divide a by b. However, since b contains some zero values, this would normally result in divide-by-zero errors.
To avoid these errors, I have used the numpy.errstate context manager to temporarily ignore divide-by-zero errors. Inside the with block, I have used np.divide(a, b) to perform the element-wise division of a by b. The resulting array c contains the result of the division, with inf values in the positions where division by zero occurred.

## Project: Array Statistics Calculator
#### Description:

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

#### Requirements:

The program should prompt the user to enter a list of numbers separated by commas.

The program should use NumPy to convert the input into a 1D NumPy array.

The program should calculate and display the following statistics:

The mean of the numbers

The median of the numbers

The standard deviation of the numbers

The maximum and minimum values of the numbers

The program should use appropriate NumPy functions to calculate the statistics.

The program should display the statistics with appropriate labels.

#### Sample Output

Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9

Statistics for the input array:

Mean: 4.5

Median: 4.0

Standard Deviation: 2.9154759474226504

Maximum: 9

Minimum: 1

## Ans.

In [7]:
import numpy as np

# Prompt the user to enter a list of numbers
nums_str = input("Enter a list of numbers separated by commas: ")

# Convert the input into a 1D NumPy array
nums = np.array(nums_str.split(','), dtype=float)

# Calculate and display the statistics
mean = np.mean(nums)
median = np.median(nums)
std_dev = np.std(nums)
max_val = np.max(nums)
min_val = np.min(nums)

print(f"Mean: {mean:.2f}")
print(f"Median: {median:.2f}")
print(f"Standard deviation: {std_dev:.2f}")
print(f"Maximum value: {max_val:.2f}")
print(f"Minimum value: {min_val:.2f}")

Mean: 2.50
Median: 2.50
Standard deviation: 1.12
Maximum value: 4.00
Minimum value: 1.00
